In [1]:
import numpy as np

In [2]:
l = ['as',1,2,3,5]

In [3]:
type(l)

list

In [5]:
type(np.array(l))

numpy.ndarray

In [13]:
a1 = np.array(l)

In [14]:
a1 = np.array([3,4,5,6,3.0])

In [9]:
a = np.array([[1,2],[3,4]])

In [10]:
a

array([[1, 2],
       [3, 4]])

In [12]:
a[1][1]

4

In [16]:
a1[1]

4.0

In [17]:
a1

array([3., 4., 5., 6., 3.])

In [25]:
a2 = np.array([[1,2,3,4]],ndmin = 4 )

In [28]:
a2[0][0][0][0]

1

In [29]:
a

array([[1, 2],
       [3, 4]])

In [30]:
np.asanyarray([1,2,4,5])

array([1, 2, 4, 5])

In [33]:
m = np.mat([[1,2,5,4],[6,7,8,9]])

In [34]:
np.asanyarray(m)

matrix([[1, 2, 5, 4],
        [6, 7, 8, 9]])

In [35]:
np.mat(a)

matrix([[1, 2],
        [3, 4]])

In [36]:
np.fromfunction(lambda i , j: i == j ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [40]:
np.mat(np.fromfunction(lambda i , j :i*j , (4,4),dtype = int))

matrix([[0, 0, 0, 0],
        [0, 1, 2, 3],
        [0, 2, 4, 6],
        [0, 3, 6, 9]])

In [50]:
np.fromfunction(lambda i , j, z :i*j*z , (3,3,2),dtype = int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [52]:
np.fromfunction(lambda i , j,z,p :i*j*z*p , (4,3,2,2),dtype = int)

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [55]:
a = np.fromfunction(lambda i , j,z :i*j*z , (4,3,2),dtype = int)

In [56]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [57]:
a.ndim

3

In [58]:
a.size

24

In [59]:
a.shape

(4, 3, 2)

In [60]:
a.dtype

dtype('int32')

In [61]:
import pandas as pd

In [62]:
pd.DataFrame(a)

ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [4]:
d = np.fromfunction(lambda i , j :i*j , (4,3),dtype = int)

In [64]:
pd.DataFrame(d)

0  1  2
0  0  0  0
1  0  1  2
2  0  2  4
3  0  3  6

In [71]:
pd.DataFrame(np.random.rand(100,5))

0         1         2         3         4
0   0.607400  0.690362  0.607300  0.603865  0.757292
1   0.089757  0.830047  0.408860  0.741264  0.421868
2   0.902787  0.800038  0.719530  0.358399  0.924337
3   0.243748  0.507680  0.080242  0.459119  0.721930
4   0.708875  0.742769  0.123383  0.351799  0.145069
..       ...       ...       ...       ...       ...
95  0.406416  0.935699  0.165262  0.011655  0.006609
96  0.543230  0.629670  0.795922  0.202732  0.221427
97  0.838649  0.674328  0.967956  0.025284  0.840245
98  0.328526  0.903401  0.156196  0.715633  0.856956
99  0.032760  0.099642  0.150748  0.622356  0.834487

[100 rows x 5 columns]

In [68]:
np.random.randint(4,50)

14

In [70]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0  1.146105  0.065062 -0.567776  1.363534  0.834894
1 -0.124961  0.332914  0.822022  1.261901 -2.246455
2  1.293278  1.174499  0.174734  1.195384 -2.020629
3 -1.834795  2.983770 -1.170411 -0.963198 -0.678446

In [79]:
a.reshape(4,2,1,3)
#combination is equal to shape of array

array([[[[0, 0, 0]],

        [[0, 0, 0]]],


       [[[0, 0, 0]],

        [[1, 0, 2]]],


       [[[0, 0, 0]],

        [[2, 0, 4]]],


       [[[0, 0, 0]],

        [[3, 0, 6]]]])

In [82]:
a.reshape(4,2,-1)

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [1, 0, 2]],

       [[0, 0, 0],
        [2, 0, 4]],

       [[0, 0, 0],
        [3, 0, 6]]])

In [87]:
c = np.arange(4,10.5,.2)

In [88]:
c[1:5]

array([4.2, 4.4, 4.6, 4.8])

In [89]:
arr = np.random.rand(4,5)

In [90]:
arr

array([[0.26145727, 0.02370888, 0.18184346, 0.74269917, 0.00682236],
       [0.39278852, 0.1531476 , 0.4015706 , 0.53603244, 0.12434929],
       [0.11240678, 0.71441483, 0.73284806, 0.53663166, 0.81948653],
       [0.27059469, 0.91163925, 0.026886  , 0.36719983, 0.49033277]])

In [92]:
arr[arr > .5]

array([0.74269917, 0.53603244, 0.71441483, 0.73284806, 0.53663166,
       0.81948653, 0.91163925])

In [93]:
arr[[1,2],[2]]

array([0.4015706 , 0.73284806])

In [94]:
arr = np.random.rand(8,5)

In [95]:
arr

array([[0.79586341, 0.3196374 , 0.60562751, 0.75541555, 0.85243145],
       [0.44949145, 0.22422357, 0.88047576, 0.83142242, 0.20423391],
       [0.70204672, 0.91567081, 0.83857582, 0.49281552, 0.84978881],
       [0.39864664, 0.46974239, 0.58669657, 0.19198765, 0.51743746],
       [0.52785732, 0.61363528, 0.02875521, 0.40170208, 0.19683357],
       [0.63235536, 0.53565745, 0.32768748, 0.01588801, 0.72102475],
       [0.0559694 , 0.31992096, 0.79717169, 0.82922784, 0.11699623],
       [0.95723212, 0.00873618, 0.82711849, 0.37688179, 0.90306311]])

In [97]:
arr[1:8 , 0:3]

array([[0.44949145, 0.22422357, 0.88047576],
       [0.70204672, 0.91567081, 0.83857582],
       [0.39864664, 0.46974239, 0.58669657],
       [0.52785732, 0.61363528, 0.02875521],
       [0.63235536, 0.53565745, 0.32768748],
       [0.0559694 , 0.31992096, 0.79717169],
       [0.95723212, 0.00873618, 0.82711849]])

In [100]:
a2 = arr[1:8,[0,1,2]]

In [102]:
a2[0][0]=100

In [103]:
a2

array([[1.00000000e+02, 2.24223572e-01, 8.80475761e-01],
       [7.02046724e-01, 9.15670814e-01, 8.38575820e-01],
       [3.98646639e-01, 4.69742387e-01, 5.86696573e-01],
       [5.27857318e-01, 6.13635275e-01, 2.87552131e-02],
       [6.32355355e-01, 5.35657454e-01, 3.27687484e-01],
       [5.59693953e-02, 3.19920956e-01, 7.97171685e-01],
       [9.57232120e-01, 8.73618216e-03, 8.27118495e-01]])

In [104]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,3],[4,5]])

In [106]:
c = np.mat(a)
d = np.mat(b)

In [107]:
c*d

matrix([[10, 13],
        [22, 29]])

In [108]:
a*b

array([[ 2,  6],
       [12, 20]])

In [111]:
m = a@b#@ is use for matrix multiplication

In [112]:
m/0

C:\Users\VIJITK~1\AppData\Local\Temp/ipykernel_11252/3791875896.py:1: RuntimeWarning: divide by zero encountered in true_divide
  m/0


array([[inf, inf],
       [inf, inf]])

In [1]:
import numpy as np

In [9]:
np.fromfunction(lambda i , j ,k , p: i*j*k*p ,(4,3,2,3),dtype = 'int'),

(array([[[[ 0,  0,  0],
          [ 0,  0,  0]],
 
         [[ 0,  0,  0],
          [ 0,  0,  0]],
 
         [[ 0,  0,  0],
          [ 0,  0,  0]]],
 
 
        [[[ 0,  0,  0],
          [ 0,  0,  0]],
 
         [[ 0,  0,  0],
          [ 0,  1,  2]],
 
         [[ 0,  0,  0],
          [ 0,  2,  4]]],
 
 
        [[[ 0,  0,  0],
          [ 0,  0,  0]],
 
         [[ 0,  0,  0],
          [ 0,  2,  4]],
 
         [[ 0,  0,  0],
          [ 0,  4,  8]]],
 
 
        [[[ 0,  0,  0],
          [ 0,  0,  0]],
 
         [[ 0,  0,  0],
          [ 0,  3,  6]],
 
         [[ 0,  0,  0],
          [ 0,  6, 12]]]]),)

In [5]:
d

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4],
       [0, 3, 6]])

In [10]:
l = [1,2,3]
np.asanyarray(l)

array([1, 2, 3])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [16]:
5+np.zeros((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [17]:
np.empty((4,5))

array([[1.03912661e-311, 6.27463370e-322, 0.00000000e+000,
        0.00000000e+000, 1.20156161e-306],
       [1.15998412e-028, 4.31603868e-080, 1.94919985e-153,
        1.03063392e-113, 1.05117820e-153],
       [6.01391519e-154, 7.65733063e-096, 1.03080435e+136,
        6.01347002e-154, 1.05146955e-153],
       [5.79937868e+294, 3.45365695e+175, 2.77191367e+296,
        2.91237123e+257, 4.71294503e+257]])

In [37]:
np.linspace(2,6,num = 100,endpoint=False,retstep=True)

(array([2.  , 2.04, 2.08, 2.12, 2.16, 2.2 , 2.24, 2.28, 2.32, 2.36, 2.4 ,
        2.44, 2.48, 2.52, 2.56, 2.6 , 2.64, 2.68, 2.72, 2.76, 2.8 , 2.84,
        2.88, 2.92, 2.96, 3.  , 3.04, 3.08, 3.12, 3.16, 3.2 , 3.24, 3.28,
        3.32, 3.36, 3.4 , 3.44, 3.48, 3.52, 3.56, 3.6 , 3.64, 3.68, 3.72,
        3.76, 3.8 , 3.84, 3.88, 3.92, 3.96, 4.  , 4.04, 4.08, 4.12, 4.16,
        4.2 , 4.24, 4.28, 4.32, 4.36, 4.4 , 4.44, 4.48, 4.52, 4.56, 4.6 ,
        4.64, 4.68, 4.72, 4.76, 4.8 , 4.84, 4.88, 4.92, 4.96, 5.  , 5.04,
        5.08, 5.12, 5.16, 5.2 , 5.24, 5.28, 5.32, 5.36, 5.4 , 5.44, 5.48,
        5.52, 5.56, 5.6 , 5.64, 5.68, 5.72, 5.76, 5.8 , 5.84, 5.88, 5.92,
        5.96]),
 0.04)

In [24]:
a = np.arange(1,6,.2)

In [26]:
b = np.arange(6,9,0.2)

In [42]:
np.logspace(2,4,10,base= 10)

array([  100.        ,   166.81005372,   278.25594022,   464.15888336,
         774.26368268,  1291.54966501,  2154.43469003,  3593.8136638 ,
        5994.84250319, 10000.        ])

In [44]:
np.linspace(2,4,10,retstep=True)

(array([2.        , 2.22222222, 2.44444444, 2.66666667, 2.88888889,
        3.11111111, 3.33333333, 3.55555556, 3.77777778, 4.        ]),
 0.2222222222222222)

In [56]:
a = np.random.rand(4,4)

In [57]:
a

array([[0.75668484, 0.57455651, 0.41423385, 0.51563612],
       [0.50653955, 0.93343234, 0.23289492, 0.52262372],
       [0.52347962, 0.93916736, 0.80682722, 0.69044316],
       [0.8160601 , 0.90825249, 0.65251173, 0.12480871]])

In [58]:
a.max()

0.9391673635597643

In [62]:
b = np.arange(4,40).reshape(3,6,2)

In [63]:
b.size

36

In [65]:
b

array([[[ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [74]:
b.max(axis = 0)

array([[28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [68]:
c =  np.arange(4,40).reshape(6,6)

In [72]:
c.max(axis=1)

array([ 9, 15, 21, 27, 33, 39])

In [73]:
c.max(axis=0)

array([34, 35, 36, 37, 38, 39])

In [71]:
c

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [75]:
10+c

array([[14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [76]:
c/2

array([[ 2. ,  2.5,  3. ,  3.5,  4. ,  4.5],
       [ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5],
       [ 8. ,  8.5,  9. ,  9.5, 10. , 10.5],
       [11. , 11.5, 12. , 12.5, 13. , 13.5],
       [14. , 14.5, 15. , 15.5, 16. , 16.5],
       [17. , 17.5, 18. , 18.5, 19. , 19.5]])

In [77]:
c/0

C:\Users\VIJITK~1\AppData\Local\Temp/ipykernel_7580/97081324.py:1: RuntimeWarning: divide by zero encountered in true_divide
  c/0


array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [78]:
 b= np.array([2,3,1,2,3,4])

In [79]:
c+b

array([[ 6,  8,  7,  9, 11, 13],
       [12, 14, 13, 15, 17, 19],
       [18, 20, 19, 21, 23, 25],
       [24, 26, 25, 27, 29, 31],
       [30, 32, 31, 33, 35, 37],
       [36, 38, 37, 39, 41, 43]])

In [84]:
b = b.reshape(1,-1)

In [89]:
b = b.T

In [90]:
c+b

array([[ 6,  7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17, 18],
       [17, 18, 19, 20, 21, 22],
       [24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36],
       [38, 39, 40, 41, 42, 43]])

In [91]:
c

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [92]:
np.log(c)

array([[1.38629436, 1.60943791, 1.79175947, 1.94591015, 2.07944154,
        2.19722458],
       [2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
        2.7080502 ],
       [2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
        3.04452244],
       [3.09104245, 3.13549422, 3.17805383, 3.21887582, 3.25809654,
        3.29583687],
       [3.33220451, 3.36729583, 3.40119738, 3.4339872 , 3.4657359 ,
        3.49650756],
       [3.52636052, 3.55534806, 3.58351894, 3.61091791, 3.63758616,
        3.66356165]])

In [93]:
x = np.array([1,2,3])

In [94]:
y = x

In [95]:
y

array([1, 2, 3])

In [96]:
z = np.copy(x)

In [97]:
z

array([1, 2, 3])

In [98]:
x[0] = 100

In [99]:
y

array([100,   2,   3])

In [100]:
z

array([1, 2, 3])

In [101]:
x

array([100,   2,   3])

In [102]:
id(z)

2103275356208

In [103]:
id(x)

2103275359280

In [104]:
id(y)

2103275359280

In [105]:
id(x[0])

2103269784176

In [106]:
id(y[0])

2103269782224

In [107]:
id(z[0])

2103269785456

In [108]:
id(y[0])==id(x[0])

True

In [113]:
id(y[0]) == id(z[2])

True

In [117]:
c = 'sudh'
id(c[0])== id(d[0])

False

In [118]:
d = ' viji'